"""packet generation info

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-24 20:25:08.014544
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))  # existing rows

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packets', schema=None) as batch_op:
        batch_op.drop_column('generation')

    # ### end Alembic commands ###
