"""job meta and saved search params

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-24 20:36:48.045814
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))

    with op.batch_alter_table('source_boards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('params', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_boards', schema=None) as batch_op:
        batch_op.drop_column('params')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('meta')

    # ### end Alembic commands ###
